name: 'coverage'

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Generate coverage report'
        uses: ArtiomTr/jest-coverage-report-action@v2
