name: 'coverage'

on:
  pull_request_target:
    branches:
      - main

jobs:
  coverage:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Generate kkk coverage report'
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: npm
